### ISSUE TITLE
Pages abbreviation

### ISSUE THREAD

**Issue by elespdn** [gustaveroudproject/roud-oeuvres-app#108]
Page abbreviation is pp., as indicated by colleagues. Check.

**Comment by elespdn** [comment]
Use a SPARQL query and move this to onto repo

**Comment by loicjaouen** [comment]
tested locally, going on to:
- [ ] backing up
- [ ] exec requests 1 then 2

the data in question is not cached, we can proceed and check

**Comment by loicjaouen** [comment]
actually, the base is already free of `p.\d`, so we can skip request #1

**Comment by loicjaouen** [comment]
maybe we did run it already some time before?

but the two first matches would be:
|   *pagesString*   |   *new_pagesString*   |
| -- | -- |
| pp. 785-786 | ppp. 785-786 |
| pp. 94-100 | ppp. 94-100 |

let me propose something like:
```sparql
PREFIX roud-oeuvres: <http://www.knora.org/ontology/0112/roud-oeuvres#>
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
select ?pagesString ?new_pagesString
where { 
    ?resource roud-oeuvres:periodicalArticleIsInPages ?pages .
    ?pages knora-base:valueHasString ?pagesString .
    filter(regex(?pagesString, "^([^p]*)p. ([\\d]+[^\\d]+[\\d]+)"))
    bind(replace(?pagesString, "^([^p]*)p. ([\\d]+[^\\d]+[\\d]+)", "$1pp. $2") AS ?new_pagesString)
}
```


|   *pagesString*   |   *new_pagesString*   |
| --- | --- |
| p. 11 et 9 | pp. 11 et 9 |
| p. 5 et 19 | pp. 5 et 19 |
| p. 9 et 16 | pp. 9 et 16 |
| "p. 13, 15" | "pp. 13, 15" |
| p. 6 et 12 | pp. 6 et 12 |
| p. 2 et 5 | pp. 2 et 5 |
| "p. 2, 3 et 5" | "pp. 2, 3 et 5" |
| p. 16 et 34 | pp. 16 et 34 |
| p. 12 et 35 | pp. 12 et 35 |
| p. 12 et 36 | pp. 12 et 36 |
| p. 6 et 12 | pp. 6 et 12 |
| p. 12 et 15 | pp. 12 et 15 | 
| p. 1 et 3 | pp. 1 et 3 |
| p. 30 et 43-44 | pp. 30 et 43-44 |
| p. 3 et 4 | pp. 3 et 4 |
| p. 9 et 11 | pp. 9 et 11 |
| p. 9 et 13 | pp. 9 et 13 |

**Comment by elespdn** [comment]
Oops, if there are "pp." it means that we did run it already before, because in the original data there were only "p."

**Comment by elespdn** [comment]
@loicjaouen, the previous query was for cases in which there are multiple pages, separated by "-" and from what you say I think it was already run. Your proposal deals with cases in which there are multiple pages separated by "et", would be nice to tackle them as well, yes!

**Comment by loicjaouen** [comment]
backed-up again and applied:

```sparql
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX roud-oeuvres: <http://www.knora.org/ontology/0112/roud-oeuvres#>
with <http://www.knora.org/data/0112/roud-oeuvres>
delete {
    ?pages knora-base:valueHasString ?pagesString .
} 
insert {
    ?pages knora-base:valueHasString ?new_pagesString .
}
where { 
    ?resource roud-oeuvres:periodicalArticleIsInPages ?pages .
    ?pages knora-base:valueHasString ?pagesString .
    filter(regex(?pagesString, "^([^p]*)p. ([\\d]+[^\\d]+[\\d]+)"))
    bind(replace(?pagesString, "^([^p]*)p. ([\\d]+[^\\d]+[\\d]+)", "$1pp. $2") AS ?new_pagesString)
}
```

and I fixed by hand two page references missing `p. ` and `pp. ` (on `5` and `1-2`)

**Comment by elespdn** [comment]
@loicjaouen, nice, thanks!
I close this.
