### ISSUE TITLE
Apply XSL

### ISSUE THREAD

**Issue by elespdn** [gustaveroudproject/roud-oeuvres-app#11]

**Comment by gfoo** [comment]
2 solutions:
- xsl with mapping in Knora to get HTML from Knora. Can we get orignal xml then ?
- apply xsl on client side : https://developer.mozilla.org/en-US/docs/Web/XSLT/Using_the_Mozilla_JavaScript_interface_to_XSL_Transformations

**Comment by elespdn** [comment]
This is ok, but continue in #30
