### ISSUE TITLE
publication missing diary notes

### ISSUE THREAD

**Issue by loicjaouen** [gustaveroudproject/roud-oeuvres-app#303]
http://localhost:4200/archive/pub/http%253A%252F%252Frdfh.ch%252F0112%252F_CWQItLmRciQ_ALN0F03JA
section "Notes de journal" is empty where it should list:
```
Pour la partie : « Bouvreuil »
« Bouvreuil » (partie de : [CLSR GR MS 4 D/6a](https://roud.unil.ch/resources/http%253A%252F%252Frdfh.ch%252F0112%252FyK4RcqWISw-Cy2bjs1NIuA))
Pour la partie : « Sous trois lampes… »
« Walens[tadt] (14-19. II. 21) » (partie de : [CLSR GR MS 4 A/12a](https://roud.unil.ch/resources/http%253A%252F%252Frdfh.ch%252F0112%252FgDL0r7tZSomwqOJT70qfPg))
```

**Comment by loicjaouen** [comment]
that part is generated in [pub-page/pub-page.component.html#L131](https://github.com/gustaveroudproject/roud-oeuvres-app/blob/master/src/app/components/pub-page/pub-page.component.html#L131)

from data in [diaryNotes](https://github.com/gustaveroudproject/roud-oeuvres-app/blob/master/src/app/components/pub-page/pub-page.component.html#L142) and [pubPartsLight](https://github.com/gustaveroudproject/roud-oeuvres-app/blob/master/src/app/components/pub-page/pub-page.component.html#L154)

**Comment by loicjaouen** [comment]
the missing part is labeled "Pour la partie: " so it is [pubPartsLight](https://github.com/gustaveroudproject/roud-oeuvres-app/blob/master/src/app/components/pub-page/pub-page.component.html#L154) that we miss

**Comment by loicjaouen** [comment]
checked the query, its result, it is all fine

**Comment by loicjaouen** [comment]
it does not show up because of : css [liPart: display: none](https://github.com/gustaveroudproject/roud-oeuvres-app/blob/master/src/app/components/pub-page/pub-page.component.scss#L4)

which is changed by [pub-page.component.ts#L399](https://github.com/gustaveroudproject/roud-oeuvres-app/blob/master/src/app/components/pub-page/pub-page.component.ts#L399) which counts the number of sub `<span>` elements.

To unify the cases (in diary, genesis, etc), an empty span was added there, that I removed for the sake of clarity...

putting it back.

**Comment by loicjaouen** [comment]
here it was @elespdn ;)

**Comment by elespdn** [comment]
Oh, great that you found out!
