### ISSUE TITLE
Resource links

### ISSUE THREAD

**Issue by elespdn** [gustaveroudproject/roud-oeuvres-app#35]
ResourceLink directive only applies to `a[class="resourceLink"]`. This class is generated from the XSL applied to the customized mapping (TEI), while the Standard mapping will not produce it.

So it works only on resources that have a rich text content with TEI and customized mapping attached.

It won't work on Persons and resources other than EstablishedText.

Solutions :
1. apply it to all `<a>` except `a[class="pageLink"]`
2. have TEI contents for all rich text properties of all resources with internal links.

**Comment by gfoo** [comment]
For standard mapping, you could simply match `a[class="salsah-link"]` to detect internal links?

**Comment by elespdn** [comment]
Yes, much better! Done in https://github.com/gustaveroudproject/roud-oeuvres-app/pull/36/commits/570e62a5ab4e9d4bfb683cac307efb1e9e20a8b0

**Comment by elespdn** [comment]
Closed in #36
