### ISSUE TITLE
Set a default Page on TextPage init

### ISSUE THREAD

**Issue by gfoo** [gustaveroudproject/roud-oeuvres-app#42]
Find a way to set page 1 in drop down menu  to open first page and scroll to page 1 anchor

1. Drop down menu can be set to 1 :   selectedPageNum = 1
2. How to load first page page like when we use drop down menu ? (Should work... ngfor depends on selectedPageNum)
3. How to scroll to correct anchor ? (This is controlled by the directive)

**Comment by elespdn** [comment]
Viewer is not anymore on TextPage.

Now 2 works (on Ms and PubPage)

Will look at 3 when we'll have a proper viewer (cf. #73)
