### ISSUE TITLE
Move related ontology string into DataService

### ISSUE THREAD

**Issue by gfoo** [gustaveroudproject/roud-oeuvres-app#43]
Prefer to centralize into DataService all strings related to ontology instead of duplicate them everywhere.

For Instance the string ‘Person’ can be declared in DataService:
```typescript
export const PERSON_CLASS = ‘Person’;
```
And use this variable everywhere.

**Comment by elespdn** [comment]
Variabili globali di classi dell'ontologia si possono mettere in DataService, che è il solo posto in cui si parla con l'ontologia. Varianti non da usare nel gravsearch e in tutto ciò che c'è in DataService, ma dappertutto altrove usiamo varianti.
