### ISSUE TITLE
Get all pages of a query or a list of resources

### ISSUE THREAD

**Issue by gfoo** [gustaveroudproject/roud-oeuvres-app#46]
In some cases we can assume that we can load all resources instead of providing a `next` button to load the next page.

 For instance in the TextPage comp, we have to load all related persons and pages: https://github.com/gustaveroudproject/roud-oeuvres-app/blob/0d762c2d9d73a1089069d58454e1880f363efc8d/src/app/components/text-page/text-page.component.ts#L30

2 cases to manage:
+ Gravsearch query: How to know that Knora has returned all resources? We cannot know that easily, the page size is configured in the stack (usually 25 resources but the client normally does not know that). 
  - first  way is to wait for an empty page that means that the previous was the last page, see the `expand` operator https://rxjs-dev.firebaseapp.com/api/operators/expand to recursively call next page (can use `scan` to concat results https://rxjs-dev.firebaseapp.com/api/operators/scan)
  - second way, we can do a count before and then we can count how many resources we have received

+ `V2/resources/IRI(/IRI)*` route:
By def we know how many resources we have to load, we have to assume that we can call the `V2/resources` route with 25 IRIs max (page size), so depending on the number of resources we have to load, we will have to call N times the route. (To sequentially load resources use `concat`operator https://rxjs-dev.firebaseapp.com/api/index/function/concat)

**TODO**: feat request Knora to know the page size?

Code to come...

**Comment by elespdn** [comment]
This is important everywhere: for the search page, for the viewer, for every page!

**Comment by elespdn** [comment]
This applies to all queries ... pages, msparts, pubparts, etc ...
