### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by elespdn** [gustaveroudproject/roud-oeuvres-app#47]
ng-bootstrap import was removed in #28 and anyway it was not used.

Angular material css added when trying to use Knora-ui, in #19 : 

> @angular/materials (to be called from src/style.css: @import "../node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css"; or 'indigo-pink', the other styles do not render well)

Then how bootstrap works? Can't remember ...

**Comment by elespdn** [comment]
@gfoo , hope you are doing well!! (j'ai quelque nouvelle grace aux autres :)
Do you remember why we removed bootstrap at a certain point? To use Knora-ui? And how is it possible that it worked also after we removed it? Any hint welcome.

My intention would be to test and reimport it (in order to use carousel as in #63 for example.

**Comment by elespdn** [comment]
I just realized that the CSS is there, in `angular.json` !

Maybe the carousel was not working only with that, because the Bootstrap JS was missing.

**Comment by gfoo** [comment]
Never used ng-bootstrap, but for what I know boostrap is CSS and for some functions (carousel) it requires jquery... so maybe you need ng-bootstrap that behind the scene implements in ts the missing jquery lib ?  But I see jquery in your package.json ... 

If you finally don’t use knora-ui you should cleanup your deps. Just keep deps required by knora API client.

**Comment by elespdn** [comment]
> Never used ng-bootstrap, but for what I know boostrap is CSS and for some functions (carousel) it requires jquery... so maybe you need ng-bootstrap that behind the scene implements in ts the missing jquery lib ? But I see jquery in your package.json ...

Yes, I am a bit confused about why it did not work without the ng-bootstrap, but I think I'll keep the ng-bootstrap, it seems very convenient.



> If you finally don’t use knora-ui you should cleanup your deps. Just keep deps required by knora API client.

Oh yes. I still have the hope of using it at least for the manuscript viewer when it will be available. But I'll open a new issue to remember that anyway.
