### ISSUE TITLE
Display HTML in Angular

### ISSUE THREAD

**Issue by elespdn** [gustaveroudproject/roud-oeuvres-app#5]
How to display HTML content stored in Knora?
Example: once the app is running, here there is a "em" tag 
http://localhost:4200/persons/http%253A%252F%252Frdfh.ch%252F0112%252F3DeFLKhnQ765ajN8eAZTtQ
There are also internal links, I have to check the documentation again about them

**Comment by elespdn** [comment]
This should be done by using the standard mapping to render in html the data in db

**Comment by gfoo** [comment]
Use innerHTML : `<div [innerHtml]="person?.notice"></div>`

**Comment by gfoo** [comment]
Angular pipe to post-format html content : `<div [innerHtml]="person?.notice | transformHref"></div>`

**Comment by gfoo** [comment]
Convert : `<a href="http://rdfh.ch/0112/d7xa60KtToy9uOjMby8A5w" class="salsah-link">` into  `<a routerLink="persons/http://rdfh.ch/0112/d7xa60KtToy9uOjMby8A5w" >`

/!\ IRI must be encoded https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/encodeURIComponent

**Comment by elespdn** [comment]
The pipe to post-format html links should go check the class of the resource at the specified IRI and build the URI for the attribute @routerLink accordingly. For example, 

- `http://rdfh.ch/0112/rWzoy7pBReeIFBFrW69X8g`
- check the class, which in this case is `roud-oeuvres:Place`
- build the URI `class/IRI` accordingly, which in this case is `person/http:%2F%2Frdfh.ch%2F0112%2FrWzoy7pBReeIFBFrW69X8g`

**Comment by elespdn** [comment]
Create a generic route /resources/IRI, that verify the class and redirect to the correct page /class/IRI

- In html: <a routerLink="resources/IRI">
- In router: query to Knora, check class, redirect

**Comment by gfoo** [comment]
Have a look to this issue : https://github.com/dhlab-basel/beol/issues/164#issuecomment-561130487

**Comment by elespdn** [comment]
@gfoo help directives to manage changes in html

**Comment by gfoo** [comment]
1. Directive official tutorial (example to change the style) : https://angular.io/guide/attribute-directives

2. To change element content, you can use `querySelectorAll` to find the `anchor` elements and `Render2` to modify the element itself. In the following example I fix href value `#link` by `{current URL}#link`:
```typescript
import { AfterViewInit, Directive, ElementRef, Renderer2 } from '@angular/core';

@Directive({
  selector: '[llCompleteFragmentAnchor]'
})
export class CompleteFragmentAnchorDirective implements AfterViewInit {
  constructor(private renderer: Renderer2, private element: ElementRef) {}

  ngAfterViewInit(): void {
    this.fixFragmentAnchor(this.element);
  }

  fixFragmentAnchor(element: ElementRef) {
    element.nativeElement.querySelectorAll('a').forEach((aElt: HTMLElement) => {
      const href = aElt.attributes['href'].value;
      if (href.startsWith('#')) {
        this.renderer.setAttribute(
          aElt,
          'href',
          // remove from the end of href a possible fragment link
          window.location.href.split('#')[0] +
            // append local href
            href
        );
      }
    });
  }
}
```

**Comment by elespdn** [comment]
Thanks!

Trying to implement this (point 1, replacing href with routerLink), see branch [linkDirective](https://github.com/gustaveroudproject/roud-oeuvres-app/compare/linkDirective). But setAttribute would not accept squared brackets.

HTML should become `<a [routerLink]="[resources/IRI]">`

but when I use `this.renderer.setAttribute(aElt, '[routerLink]','resources/'+IRI);`, it does not work anymore ... any hints @gfoo ?

**Comment by gfoo** [comment]
> HTML should become <a [routerLink]="[resources/IRI]">

in Angular `[attr]="var"` is a variable binding (https://angular.io/guide/template-syntax#binding-syntax-an-overview), not necessary in this case, we use binding a lot with @Input vars for instance.

You could just use `<a routerLink="resources/IRI"> which means in Angular `set resources/IRI to variable routerLink`, so just try `this.renderer.setAttribute(aElt, 'routerLink','resources/'+IRI);`

**Comment by gfoo** [comment]
Also, don't forget to encode IRI:
```javascript
const encodedIRI = encodeURIComponent(IRI); // no need to import encodeURIComponent, part of core browser js lib
 this.renderer.setAttribute(aElt, 'routerLink','resources/'+encodedIRI);
```

**Comment by gfoo** [comment]
I prefer string template to avoid `+` operator sometimes chaotics in js 👎 
```js
const encodedIRI = encodeURIComponent(IRI); // no need to import encodeURIComponent, part of core browser js lib
 this.renderer.setAttribute(aElt, 'routerLink',`resources/${encodedIRI}`); // use ` backslash for str template
```
oh what a funny devloper !

**Comment by elespdn** [comment]
OK!

IRI encoded and string template set. https://github.com/gustaveroudproject/roud-oeuvres-app/commit/7ba73672ac9e6077cfe871b77ecd4d255cd7926a

The link does not appear anymore (see e.g. person "Olivier Cherpillod", Vucherens should be a link), but I guess I'll fix this later (point 2).

Also, for the record, I replaced `resources/IRI` with `/resources/IRI`. https://github.com/gustaveroudproject/roud-oeuvres-app/commit/4e3bb1f88aa78ae875ffe68649ef8b8be9d9ff65

**Comment by elespdn** [comment]
Point 2.
Let's see if I got it.

1. In `app-routing.module.ts` define that when @routerLink has value "resources/IRI" should call resource-router-component.
1. In resource-router-component:
    1. define the mapping between the type of the resource and the path, e.g. `('Person', '/persons/')`
    1. check type of the resource (see below)
    1. create new IRI to redirect to
1. To check type of resource:
    1. take the IRI


Quindi ... --> bring path back to "resources/IRI", not "/resources/IRI"

**Comment by gfoo** [comment]
Oups, tested your code and I made a mistake by proposing the `routerLink` !
In fact, we have to use `routerLink` when WE write templates of components, then on the fly, Angular will replace this `routerLink` by a `href` (and other stuffs).

In our case we just want to transform an existing `href` of html code already rendered (Angular had already done its job), so just do that:
```javascript
    this.renderer.setAttribute(aElt, 'href',`/resources/${encodedIRI}`);
```
Sorry!

**Comment by elespdn** [comment]
Great news, thanks! Updated in https://github.com/gustaveroudproject/roud-oeuvres-app/commit/f408f74e3cc9def422eea45d573c67af39e09b5e

**Comment by elespdn** [comment]
Point 2 fixed in: https://github.com/gustaveroudproject/roud-oeuvres-app/commit/7b256ca35ee2dbe7737870414df5c886f62dd7ab
