### ISSUE TITLE
Update Knora and knora-api-js-lib

### ISSUE THREAD

**Issue by elespdn** [gustaveroudproject/roud-oeuvres-app#54]

**Comment by elespdn** [comment]
@loicjaouen, do you agree that I have to regularly update my local Knora stack and the [knora-api-js-lib](https://github.com/dasch-swiss/knora-api-js-lib) ?

Any recommendation? I guess I should test if it work on a dedicated branch? Might be a stupid question, but prefer to check with you before doing something even more stupid :) Thanks*

**Comment by loicjaouen** [comment]
The goal is that:
- you don't spend your time tracking our latest changes
- once released, your app runs as long as possible without (code) maintenance

Right now [knora-api-js-lib](https://github.com/dasch-swiss/knora-api-js-lib) is in pre-release phase, there are already some changes (as far as we are concerned, mainly the name change `@dasch-swiss/dsp-js` and introduction of intermediate class `ReadResourceSequence`).  
It is best to wait for a the v1.0.0 release for stable interfaces.

The other leg is that your work is compatible with the version of the knora used on prod. You are currently using a v12 knora stack, production is still at v11. It will eventually be upgraded to v13, but we will test and coordinate that.

So for now, it is best to keep your current set-up (knora stack v12, knora-api-js-lib v0.2.0).

We will coordinate the change to v13 and @dasch-swiss/dsp-js v1.0.0 later on this year and this will be stable for some time again.

At the time of the final release, we will again check the latest version of those two elements to increase the longevity of the app (earlier if there is a breaking change).

**Comment by elespdn** [comment]
Thanks, d'accord !
