### ISSUE TITLE
Dates formatting

### ISSUE THREAD

**Issue by elespdn** [gustaveroudproject/roud-oeuvres-app#6]
Is it ok to extract substrings like this to avoid having "gregorian" and "CE" on all dates?
https://github.com/gustaveroudproject/roud-oeuvres-app/commit/adf4776d1b3551f31761e9c9633bee9f0f3d7b76

**Comment by gfoo** [comment]
Angular pipe to post-format #5

**Comment by elespdn** [comment]
Ok, fixed in #14
